# (PART) Statistika me R {-}

# Hyrje në Statistikë me R

Analiza e të dhënave është një nga fokuset kryesore të këtij libri. Nëse disa metoda të llogaritjeve që do prezantojmë janë zhvillime relativisht të fundit, analiza e të dhënave ka ekzistuar për rreth një shekull. Përgjatë viteve, analistët e të dhënave duke punuar në projekte specifike kanë dalë me ide dhe koncepte që përgjithësohen në shumë aplikacione. Ata gjithashtu kanë identifikuar mënyrat e zakonshme se si modelet mund të na shpien në përfundime të gabuara apo përfundime të rëndësishme matematikore që nuk janë menjëherë të dukshme. Akumulimi i këtyre ideve dhe përfundimeve ka krijuar fushën e Statistikës, e cila siguron një kornizë matematikore që lehtëson shumë përshkrimin dhe vlerësimin formal të këtyre ideve.

Për të shmangur përsëritjen e gabimeve të zakonshme dhe humbjen e kohës për të rizbuluar rrotën, është e rëndësishme që një analist i të dhënave të ketë një kuptim të thelluar të statistikave.  Ne do prezantojmë konceptet shkurtimisht dhe pastaj do të punojmë në mënyrë të detajuar me disa shembuj që demonstrojnë se si statistikat përdoren në analizën e të dhënave së bashku me kodin R që implementon këto ide. Ne gjithashtu do të përdorim R për të sqaruar disa prej koncepteve kryesore statistikore që zakonisht përshkruhen duke përdorur matematikën. 

Konceptet specifike të përfshira në këtë pjesë janë Probabiliteti, Statistika e Përfundimeve, Modelet Statistikore, Regresioni dhe Modelet lineare, të cilat janë temat kryesore që do trajtojmë. Studimet e rasteve që paraqesim kanë të bëjnë me krizën financiare, parashikimin e rezultateve të zgjedhjeve, kuptimin e trashëgimisë dhe ndërtimin e një ekipi të bejzbollit.

